"""initial schema

Revision ID: d590d6e06ac2
Revises: 
Create Date: 2026-08-11 22:51:43.449314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd590d6e06ac2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('actor', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_entry_created_at'), 'audit_log_entry', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_entry_entity_id'), 'audit_log_entry', ['entity_id'], unique=False)
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('cik', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('sector', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('exchange', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_cik'), 'company', ['cik'], unique=True)
    op.create_index(op.f('ix_company_ticker'), 'company', ['ticker'], unique=True)
    op.create_table('filing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('accession_number', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('form_type', sa.Enum('FORM_10K', 'FORM_10Q', 'FORM_8K', 'FORM_20F', 'FORM_DEF14A', 'OTHER', name='filingtype'), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('period_of_report', sa.Date(), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filing_accession_number'), 'filing', ['accession_number'], unique=True)
    op.create_index(op.f('ix_filing_company_id'), 'filing', ['company_id'], unique=False)
    op.create_table('segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_segment_company_name')
    )
    op.create_index(op.f('ix_segment_company_id'), 'segment', ['company_id'], unique=False)
    op.create_table('valuation_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('DCF', 'COMPS', 'SOTP', name='valuationmethod'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=True),
    sa.Column('outputs', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_valuation_run_company_id'), 'valuation_run', ['company_id'], unique=False)
    op.create_table('assumption_decision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valuation_run_id', sa.Integer(), nullable=False),
    sa.Column('assumption_key', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('ai_recommended_value', sa.Float(), nullable=True),
    sa.Column('ai_rationale', sqlmodel.sql.sqltypes.AutoString(length=4096), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('approved_value', sa.Float(), nullable=True),
    sa.Column('approval_reason', sqlmodel.sql.sqltypes.AutoString(length=4096), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'OVERRIDDEN', 'REJECTED', name='assumptionstatus'), nullable=False),
    sa.Column('decided_by', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['valuation_run_id'], ['valuation_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assumption_decision_valuation_run_id'), 'assumption_decision', ['valuation_run_id'], unique=False)
    op.create_table('financial_fact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=True),
    sa.Column('concept', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_period', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('accession_number', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('xbrl_tag', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('data_status', sa.Enum('REPORTED', 'DERIVED', 'ESTIMATED', 'MISSING', 'CONFLICTING', name='datastatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['filing_id'], ['filing.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'concept', 'period', 'xbrl_tag', name='uq_financial_fact_natural_key')
    )
    op.create_index(op.f('ix_financial_fact_accession_number'), 'financial_fact', ['accession_number'], unique=False)
    op.create_index(op.f('ix_financial_fact_company_id'), 'financial_fact', ['company_id'], unique=False)
    op.create_index(op.f('ix_financial_fact_concept'), 'financial_fact', ['concept'], unique=False)
    op.create_index(op.f('ix_financial_fact_filing_id'), 'financial_fact', ['filing_id'], unique=False)
    op.create_table('segment_financial_fact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=True),
    sa.Column('concept', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_period', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('accession_number', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('xbrl_tag', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('data_status', sa.Enum('REPORTED', 'DERIVED', 'ESTIMATED', 'MISSING', 'CONFLICTING', name='datastatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filing.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['segment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('segment_id', 'concept', 'period', 'xbrl_tag', name='uq_segment_financial_fact_natural_key')
    )
    op.create_index(op.f('ix_segment_financial_fact_accession_number'), 'segment_financial_fact', ['accession_number'], unique=False)
    op.create_index(op.f('ix_segment_financial_fact_concept'), 'segment_financial_fact', ['concept'], unique=False)
    op.create_index(op.f('ix_segment_financial_fact_filing_id'), 'segment_financial_fact', ['filing_id'], unique=False)
    op.create_index(op.f('ix_segment_financial_fact_segment_id'), 'segment_financial_fact', ['segment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segment_financial_fact_segment_id'), table_name='segment_financial_fact')
    op.drop_index(op.f('ix_segment_financial_fact_filing_id'), table_name='segment_financial_fact')
    op.drop_index(op.f('ix_segment_financial_fact_concept'), table_name='segment_financial_fact')
    op.drop_index(op.f('ix_segment_financial_fact_accession_number'), table_name='segment_financial_fact')
    op.drop_table('segment_financial_fact')
    op.drop_index(op.f('ix_financial_fact_filing_id'), table_name='financial_fact')
    op.drop_index(op.f('ix_financial_fact_concept'), table_name='financial_fact')
    op.drop_index(op.f('ix_financial_fact_company_id'), table_name='financial_fact')
    op.drop_index(op.f('ix_financial_fact_accession_number'), table_name='financial_fact')
    op.drop_table('financial_fact')
    op.drop_index(op.f('ix_assumption_decision_valuation_run_id'), table_name='assumption_decision')
    op.drop_table('assumption_decision')
    op.drop_index(op.f('ix_valuation_run_company_id'), table_name='valuation_run')
    op.drop_table('valuation_run')
    op.drop_index(op.f('ix_segment_company_id'), table_name='segment')
    op.drop_table('segment')
    op.drop_index(op.f('ix_filing_company_id'), table_name='filing')
    op.drop_index(op.f('ix_filing_accession_number'), table_name='filing')
    op.drop_table('filing')
    op.drop_index(op.f('ix_company_ticker'), table_name='company')
    op.drop_index(op.f('ix_company_cik'), table_name='company')
    op.drop_table('company')
    op.drop_index(op.f('ix_audit_log_entry_entity_id'), table_name='audit_log_entry')
    op.drop_index(op.f('ix_audit_log_entry_created_at'), table_name='audit_log_entry')
    op.drop_table('audit_log_entry')
    # ### end Alembic commands ###
